# Generated by Django 2.0.7 on 2018-09-13 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(verbose_name='用户id')),
                ('goodsid', models.IntegerField(verbose_name='商品id')),
                ('number', models.IntegerField(verbose_name='商品份数')),
                ('state', models.IntegerField(verbose_name='操作状态')),
                ('operation_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '购买信息',
                'verbose_name_plural': '购买信息',
            },
        ),
    ]
