# Generated by Django 2.0.7 on 2018-09-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(max_length=6, verbose_name='用户id')),
                ('goodsid', models.IntegerField(max_length=6, verbose_name='商品id')),
                ('number', models.IntegerField(max_length=6, verbose_name='商品份数')),
                ('state', models.IntegerField(max_length=2, verbose_name='商品状态')),
            ],
            options={
                'verbose_name': '购买状态',
                'verbose_name_plural': '购买状态',
            },
        ),
    ]
