# Generated by Django 2.0.7 on 2018-09-13 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180913_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'verbose_name': '购买信息', 'verbose_name_plural': '购买信息'},
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='操作时间'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='state',
            field=models.IntegerField(verbose_name='操作状态'),
        ),
    ]
