# Generated by Django 2.0.7 on 2018-09-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneverifycode',
            old_name='send_time',
            new_name='add_time',
        ),
    ]
